services:
  duckdb:
    image: duckdb/duckdb:latest
    container_name: duckdb-agro
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /data
    command: ["/duckdb", ":memory:"]
    ports:
      - "4213:4213"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./sql:/sql
      - ../validation:/validation
